sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t carboncoop/docker-smxcore .
# test image
- docker run carboncoop/docker-smxcore
#--version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag carboncoop/smx-emonhub carboncoop/smx-emonhub:$TAG
    docker push carboncoop/smx-emonhub:$TAG
    docker push carboncoop/smx-emonhub
  fi
